version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: yarn start
    ports:
      - 7999:9999
#docker-compose up // docker-compose up -d ( -d here means run with detach )
#
      